export default
{
    apiAuthLogin: "/api/auth/login",
    apiAuthResetPassword: "/api/auth/reset-password",
    apiAuthValidateResetPasswordToken: "/api/auth/validate-reset-password-token",
    apiAuthChangePassword: "/api/auth/change-password",
    apiAuthChangeUserPassword: "/api/auth/change-user-password",
    apiAuthLogout: "/api/auth/logout",
    apiAuthCheck: "/api/auth/check",
    apiAuthRefreshAccessToken: "/api/auth/refresh-access-token",
    apiUserInfo: "/api/user/info",

    apiCompanyAdd: "/api/company/add",
    apiCompanyEdit: "/api/company/edit",
    apiCompanyGet: "/api/company/get",
    apiCompanyDetail: "/api/company/detail",
    apiCompanyDelete: "/api/company/delete",
    apiCompanyList: "/api/company/list",

    apiPetroStationAdd: "/api/petro-station/add",
    apiPetroStationEdit: "/api/petro-station/edit",
    apiPetroStationGet: "/api/petro-station/get",
    apiPetroStationDetail: "/api/petro-station/detail",
    apiPetroStationDelete: "/api/petro-station/delete",
    apiPetroStationPayment: "/api/petro-station/payment",
    apiPetroStationList: "/api/petro-station/list",

    apiStationUserAdd: "/api/station-user/add",
    apiStationUserEdit: "/api/station-user/edit",
    apiStationUserGet: "/api/station-user/get",
    apiStationUserDetail: "/api/station-user/detail",
    apiStationUserDelete: "/api/station-user/delete",

    apiBranchAdd: "/api/branch/add",
    apiBranchEdit: "/api/branch/edit",
    apiBranchGet: "/api/branch/get",
    apiBranchDetail: "/api/branch/detail",
    apiBranchDelete: "/api/branch/delete",
    apiBranchActive: "/api/branch/active",
    apiBranchList: "/api/branch/list",
    apiBranchChargeBalance: "/api/branch/charge-balance",

    apiCarAdd: "/api/car/add",
    apiCarEdit: "/api/car/edit",
    apiCarGet: "/api/car/get",
    apiCarDetail: "/api/car/detail",
    apiCarDelete: "/api/car/delete",
    apiCarList: "/api/car/list",
    apiCarActive: "/api/car/active",

    apiBundleAdd: "/api/bundle/add",
    apiBundleEdit: "/api/bundle/edit",
    apiBundleGet: "/api/bundle/get",
    apiBundleDetail: "/api/bundle/detail",
    apiBundleDelete: "/api/bundle/delete",

    apiRechargeBalanceAdd: "/api/recharge-balance/add",
    apiRechargeBalanceEdit: "/api/recharge-balance/edit",
    apiRechargeBalanceGet: "/api/recharge-balance/get",
    apiRechargeBalanceDetail: "/api/recharge-balance/detail",
    apiRechargeBalanceDelete: "/api/recharge-balance/delete",
    apiRechargeBalanceConfirm: "/api/recharge-balance/confirm",

    apiSubscriptionAdd: "/api/subscription/add",
    apiSubscriptionEdit: "/api/subscription/edit",
    apiSubscriptionGet: "/api/subscription/get",
    apiSubscriptionDetail: "/api/subscription/detail",
    apiSubscriptionDelete: "/api/subscription/delete",
    apiSubscriptionActive: "/api/subscription/active",
    apiSubscriptionCalculate: "/api/subscription/calculate",
    apiSubscriptionCarAdd: "/api/subscription/car-add",

    apiAccountBalanceGet: "/api/account-balance/get",
    apiInvoiceSummaryGet: "/api/invoice-summary/get",
    apiInvoiceDetailGet: "/api/invoice-detail/get",
    apiCarBalanceGet: "/api/car-balance/get",
    apiStationReportGet: "/api/station-report/get",
    apiStationSaleGet: "/api/station-sale/get",
    apiStationStatementGet: "/api/station-statement/get",
    apiCarTransactionGet: "/api/car-transaction/get",
    apiPetrolStationListGet: "/api/petrol-station-list/get",

    apiPetropayAccountGet: "/api/petropay-account/get",
    apiPetropayAccountList: "/api/petropay-account/list",
    apiPetropayAccountPayment: "/api/petropay-account/payment",

    apiServiceMasterList: "/api/service-master/list",

    apiTransferBalance: "/api/transfer-balance",

    apiPromotionCouponAdd: "/api/promotion-coupon/add",
    apiPromotionCouponEdit: "/api/promotion-coupon/edit",
    apiPromotionCouponGet: "/api/promotion-coupon/get",
    apiPromotionCouponDetail: "/api/promotion-coupon/detail",
    apiPromotionCouponDelete: "/api/promotion-coupon/delete",

    apiDashboardCustomerGet: "/api/dashboard/customer",
    apiDashboardSupplierGet: "/api/dashboard/supplier",
    apiDashboardAdminGet: "/api/dashboard/admin",

    apiLog: "/api/log"
}
