export default {
    appStore: 'appStore',
    pageStore: 'pageStore',
    authStore: 'authStore',
    customerStore: 'customerStore',
    supplierStore: 'supplierStore',
    adminStore: 'adminStore',
    companiesStore: 'companiesStore',
    bundlesStore: 'bundlesStore',
    branchStore: 'branchStore',
    petroStationStore: 'petroStationStore',
    stationUserStore: 'stationUserStore',
    carStore: 'carStore',
    rechargeBalanceStore: 'rechargeBalanceStore',
    subscriptionStore: 'subscriptionStore',
    invoiceSummaryStore: 'invoiceSummaryStore',
    invoiceDetailStore: 'invoiceDetailStore',
    carBalanceStore: 'carBalanceStore',
    stationReportStore: 'stationReportStore',
}
